Improved init scripts and added status option.
- Fixed the init scripts which were set to "exit 0" on all errors,
  causing confusion for scripts and programs looking to check the
  service when it's disabled.
- Asses support for status option to check the status of the running
  services.

diff --git a/debian/libmogilefs-server-perl.mogstored.init b/debian/libmogilefs-server-perl.mogstored.init
--- a/debian/libmogilefs-server-perl.mogstored.init
+++ b/debian/libmogilefs-server-perl.mogstored.init
@@ -4,7 +4,7 @@
 #		This file should be used to construct scripts for /etc/init.d.
 #
 #		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
-#		Modified for Debian 
+#		Modified for Debian
 #		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
 #
 # Version:	@(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
@@ -15,76 +15,83 @@
 # Required-Stop:     $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Manage mogstored state
-# Description:       Starts and stops mogstored
+# Short-Description: Manage the mogstored service
+# Description:       Starts and stops MogileFS storage daemon.
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/bin/mogstored
 NAME=mogstored
 DESC=mogstored
-PIDFILE=/var/run/$NAME.pid
 DEFAULTS=/etc/default/$NAME
+PIDFILE=/var/run/$NAME.pid
 
+test -x $DAEMON || exit 1
 
-test -x $DAEMON || exit 0
+if [ ! -e $DEFAULTS ]; then
+	echo "Can't start $NAME. Defaults file ($DEFAULTS) doesn't exist."
+	echo "Please run dpkg-reconfigure $NAME to correct the problem."
+	exit 1
+fi
 
-[ -e $DEFAULTS ] && . $DEFAULTS
+[ -r $DEFAULTS ] && . $DEFAULTS
 
-if [ "x$START" != "xYES" ]
-  then
-  exit 0
+if [ "x$START" != "xYES" ]; then
+  echo "Disabled: $NAME." >&2
+  exit 1
 fi
 
 set -e
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
+		echo -n "Starting $DESC: "
 
-	if [ -e $PIDFILE ]
-		then
-		
-		if [ -d /proc/`cat $PIDFILE`/ ]
-		then
-
-			echo "$NAME already running."
-			exit 0;
-		else
-			rm -f $PIDFILE
+		if [ -e $PIDFILE ]; then
+			if [ -d /proc/`cat $PIDFILE`/ ]; then
+				echo "$NAME already running."
+				exit 1;
+			else
+				rm -f $PIDFILE
+			fi
 		fi
 
-	fi
+		start-stop-daemon --start --quiet --exec $DAEMON --pidfile $PIDFILE -b -m --name $NAME
+		echo "$NAME."
+		;;
 
-	start-stop-daemon --start --quiet --exec $DAEMON --pidfile $PIDFILE -b -m --name $NAME
-	echo "$NAME."
-	;;
   stop)
-	echo -n "Stopping $DESC: "
-	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --name $NAME
-	echo "$NAME."
-	rm -f $PIDFILE
-	;;
+		echo -n "Stopping $DESC: "
+		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --name $NAME
+		echo "$NAME."
+		rm -f $PIDFILE
+		;;
 
   restart|force-reload)
-	#
-	#	If the "reload" option is implemented, move the "force-reload"
-	#	option to the "reload" entry above. If not, "force-reload" is
-	#	just the same as "restart".
-	#
-	echo -n "Restarting $DESC: "
-	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --name $NAME
-	rm -f $PIDFILE
-	sleep 1
-	start-stop-daemon --start --quiet --exec $DAEMON --pidfile $PIDFILE -b -m --name $NAME
-	echo "$NAME."
-	;;
+		echo -n "Restarting $DESC: "
+		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --name $NAME
+		rm -f $PIDFILE
+		sleep 1
+		start-stop-daemon --start --quiet --exec $DAEMON --pidfile $PIDFILE -b -m --name $NAME
+		echo "$NAME."
+		;;
+
+	status)
+		echo -n "Status $DESC: "
+		if [ -e $PIDFILE ]; then
+			if [ -d /proc/`cat $PIDFILE`/ ]; then
+				echo "$NAME is running."
+				exit 0;
+			fi
+		fi
+		echo "$NAME is NOT running."
+		exit 1;
+		;;
+
   *)
-	N=/etc/init.d/$NAME
-	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N {start|stop|restart|force-reload}" >&2
-	exit 1
-	;;
+		echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
+		exit 1
+		;;
 esac
 
 exit 0
